import { mkdir, readFile, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import * as mdi from "@mdi/js";
import * as simpleIcons from "simple-icons";

const require = createRequire(import.meta.url);
const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const frontendDirectory = dirname(scriptDirectory);
const repositoryDirectory = dirname(frontendDirectory);
const iconDirectory = join(frontendDirectory, "public", "icons");
const fontDirectory = join(frontendDirectory, "public", "fonts");
const generatedManifestPath = join(frontendDirectory, "src", "generated", "icon-manifest.ts");
const backendManifestPath = join(repositoryDirectory, "backend", "app", "icon_manifest.py");
const checkOnly = process.argv.includes("--check");

// This intentionally small list is the complete runtime allowlist. It keeps
// the browser bundle and attack surface bounded while still covering the
// device and platform types used by the topology editor.
const iconDefinitions = [
  { id: "mdi-server", label: "Server", glyph: "▦", source: "mdi", exportName: "mdiServer" },
  { id: "mdi-router", label: "Router", glyph: "⌁", source: "mdi", exportName: "mdiRouter" },
  { id: "mdi-switch", label: "Switch", glyph: "⇄", source: "mdi", exportName: "mdiSwitch" },
  { id: "mdi-laptop", label: "Workstation", glyph: "▣", source: "mdi", exportName: "mdiLaptop" },
  { id: "mdi-database", label: "Database", glyph: "▤", source: "mdi", exportName: "mdiDatabase" },
  { id: "mdi-cloud", label: "Cloud", glyph: "☁", source: "mdi", exportName: "mdiCloud" },
  { id: "mdi-cube", label: "Container", glyph: "◇", source: "mdi", exportName: "mdiCube" },
  { id: "mdi-kubernetes", label: "Kubernetes", glyph: "⎈", source: "mdi", exportName: "mdiKubernetes" },
  { id: "mdi-monitor", label: "Monitor", glyph: "▱", source: "mdi", exportName: "mdiMonitor" },
  { id: "mdi-service", label: "Service", glyph: "✦", source: "mdi", exportName: "mdiLanConnect" },
  { id: "si-docker", label: "Docker", glyph: "◈", source: "si", exportName: "siDocker" },
  { id: "si-kubernetes", label: "Kubernetes (brand)", glyph: "◈", source: "si", exportName: "siKubernetes" },
  { id: "si-proxmox", label: "Proxmox", glyph: "◈", source: "si", exportName: "siProxmox" },
  { id: "si-github", label: "GitHub", glyph: "◈", source: "si", exportName: "siGithub" },
  { id: "si-cloudflare", label: "Cloudflare", glyph: "◈", source: "si", exportName: "siCloudflare" },
];

const fontDefinitions = [
  {
    packageName: "@fontsource-variable/inter",
    sourceFile: "files/inter-latin-wght-normal.woff2",
    outputFile: "inter-latin-wght-normal.woff2",
    licenseFile: "LICENSE",
    outputLicenseFile: "LICENSE-inter.txt",
  },
  {
    packageName: "@fontsource-variable/jetbrains-mono",
    sourceFile: "files/jetbrains-mono-latin-wght-normal.woff2",
    outputFile: "jetbrains-mono-latin-wght-normal.woff2",
    licenseFile: "LICENSE",
    outputLicenseFile: "LICENSE-jetbrains-mono.txt",
  },
];

function valueFor(definition) {
  const library = definition.source === "mdi" ? mdi : simpleIcons;
  const value = library[definition.exportName];
  if (definition.source === "mdi" && typeof value === "string") {
    return value;
  }
  if (definition.source === "si" && value && typeof value.path === "string") {
    return value.path;
  }
  throw new Error(`Missing ${definition.source} export ${definition.exportName} for ${definition.id}`);
}

function svgFor(path) {
  // Paths come only from the pinned packages above; user input never reaches
  // this generator or the runtime renderer.
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="#79cde3"><path d="${path}"/></svg>\n`;
}

function frontendManifest(definitions) {
  const rows = definitions
    .map(
      ({ id, label, glyph }) =>
        `  { id: ${JSON.stringify(id)}, label: ${JSON.stringify(label)}, glyph: ${JSON.stringify(glyph)}, assetFile: ${JSON.stringify(`${id}.svg`)} },`,
    )
    .join("\n");
  return `// Generated by scripts/generate-icons.mjs. Do not edit manually.\n\nexport interface GeneratedIcon {\n  id: string;\n  label: string;\n  glyph: string;\n  assetFile: string;\n}\n\nexport const GENERATED_ICON_MANIFEST: readonly GeneratedIcon[] = [\n${rows}\n];\n`;
}

function backendManifest(definitions) {
  const ids = definitions.map(({ id }) => `        ${JSON.stringify(id)},`).join("\n");
  return `\"\"\"Generated local icon allowlist. Do not edit manually.\"\"\"\n\nICON_IDS = frozenset(\n    {\n${ids}\n    }\n)\n`;
}

async function sourceFile(packageName, relativePath) {
  const packageJson = require.resolve(`${packageName}/package.json`);
  return join(dirname(packageJson), relativePath);
}

async function writeOrCheck(path, contents) {
  if (checkOnly) {
    let existing;
    try {
      existing = await readFile(path);
    } catch {
      throw new Error(`Missing generated asset: ${path}`);
    }
    if (!existing.equals(Buffer.isBuffer(contents) ? contents : Buffer.from(contents))) {
      throw new Error(`Generated asset is stale: ${path}`);
    }
    return;
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, contents);
}

async function main() {
  for (const definition of iconDefinitions) {
    await writeOrCheck(join(iconDirectory, `${definition.id}.svg`), svgFor(valueFor(definition)));
  }

  for (const font of fontDefinitions) {
    const fontContents = await readFile(await sourceFile(font.packageName, font.sourceFile));
    const licenseContents = await readFile(await sourceFile(font.packageName, font.licenseFile));
    await writeOrCheck(join(fontDirectory, font.outputFile), fontContents);
    await writeOrCheck(join(fontDirectory, font.outputLicenseFile), licenseContents);
  }

  await writeOrCheck(generatedManifestPath, frontendManifest(iconDefinitions));
  await writeOrCheck(backendManifestPath, backendManifest(iconDefinitions));
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  console.error("Run `pnpm generate:icons` after installing the pinned frontend dependencies.");
  process.exitCode = 1;
});
